version: '3.8'
services:
  pg:
    image: postgres
    container_name: pg
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mycontacts
  urubu:
    container_name: urubu
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - pg
    env_file:
      - .env
